### PR TITLE
Add support for PHP 8

### PR DESCRIPTION
**Pull request by marcelthole**
Hey,

the tests runs fine with PHP 8.0 and PHP 8.1
It would be awesome if you could add the new PHP Versions into the composer.json

### CODE REVIEW

**Comment by bigwhoop** [comment]
Thanks @marcelthole! Merged and released in 3.1.0

**Comment by bigwhoop** [comment]
actually pushed 3.1.1 as well as the composer.lock wasn't updated with the new version requirements yet.

no-dev installs should work with PHP 8 now. dev installs still have some dependencies that only work with PHP 7. will look into that.

**Comment by marcelthole** [comment]
sorry that i missed to update the lock file. But could i ask why the composer.lock is in this project?
i use the package as a dependency an don't need the provided lock file.

And if you want to test the application against the different PHP Versions you would run an `composer update`?
something like this in the github Workflow:
```
      - name: "Update dependencies (lowest)"
        run: "composer update --no-interaction --no-progress --no-suggest --prefer-lowest --prefer-stable"
        if: ${{ matrix.composer-deps == 'lowest' }}

      - name: "Update dependencies (latest)"
        run: "composer update --no-interaction --no-progress --no-suggest"
        if: ${{ matrix.composer-deps == 'latest' }}
```

**Comment by bigwhoop** [comment]
I think you're absolutely correct. for a library it makes no sense to commit the lock file. I guess I just did it out of habit.

thanks for your input! I'll update it accordingly.

**Pull request merged**
